name 'puppet-cobbler'
version '1.2.1'
source 'https://bitbucket.org/jsosic/puppet-cobbler/src'
author 'Jakov Sosic <jsosic@gmail.com>'
license 'Apache 2.0'
summary 'Puppet module for Cobbler'
description 'Module for Cobbler configuration'
project_page 'https://bitbucket.org/jsosic/puppet-cobbler'
